# Generated by Django 6.0.3 on 2026-03-12 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('city_state', models.CharField(max_length=255)),
                ('involvement', models.CharField(choices=[('full-time', 'Yes — Full-time realtor'), ('part-time', 'Yes — Part-time realtor'), ('interested', 'Not yet, but interested'), ('investor', 'Property investor'), ('other', 'Other')], max_length=20)),
                ('experience', models.CharField(choices=[('none', 'None'), ('<1yr', 'Less than 1 year'), ('1-3yr', '1–3 years'), ('4-7yr', '4–7 years'), ('8+yr', '8+ years')], max_length=10)),
                ('interests', models.TextField(help_text='Comma-separated interests')),
                ('challenge', models.TextField()),
                ('will_attend_all', models.BooleanField(default=False)),
                ('will_follow_ethics', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('trinity-community', 'Trinity Community'), ('rurblist', 'Rurblist'), ('friend-referral', 'Friend Referral'), ('other', 'Other')], max_length=50)),
                ('refer_friends', models.BooleanField(default=False)),
                ('referral_phones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
